version: 2

aliases:
    - &docker-node-latest
        - image: circleci/node:latest

    - &docker-node-lts
        - image: circleci/node:lts

    - &docker-node-8
        - image: circleci/node:8

    - &restore-node-modules-cache
        name: Restore node_modules cache
        key: v1-yarn-deps-{{ checksum "yarn.lock" }}

    - &restore-yarn-cache
        name: Restore yarnpkg cache
        key: v1-yarn-cache

    - &save-node-modules-cache
        name: Save node_modules cache
        paths:
            - node_modules
        key: v1-yarn-deps-{{ checksum "yarn.lock" }}

    - &save-yarn-cache
        name: Save yarnpkg cache
        paths:
            - ~/.cache/yarn
        key: v1-yarn-cache

jobs:
    checkout-code:
        docker: *docker-node-lts
        steps:
            - checkout
            - restore_cache: *restore-yarn-cache
            - restore_cache: *restore-node-modules-cache
            - run: yarn install --non-interactive --cache-folder ~/.cache/yarn
            - run:
                name: Check if yarn.lock changed during install
                command: git diff --exit-code
            - save_cache: *save-node-modules-cache
            - save_cache: *save-yarn-cache

    clean-lockfile:
        docker: *docker-node-lts
        steps:
            - checkout
            - restore_cache: *restore-node-modules-cache
            - run: ./scripts/verifyCleanLockfile.sh

    build:
        docker: *docker-node-lts
        steps:
            - checkout
            - restore_cache: *restore-node-modules-cache
            - attach_workspace: { at: '.' }
            - run: yarn compile
            - persist_to_workspace:
                root: "."
                paths: [lib, build]

    lint:
        docker: *docker-node-lts
        steps:
            - checkout
            - restore_cache: *restore-node-modules-cache
            - attach_workspace: { at: '.' }
            - run: yarn lint

    test:
        docker: *docker-node-8
        steps:
            - checkout
            - restore_cache: *restore-node-modules-cache
            - attach_workspace: { at: '.' }
            - run: yarn test

    test2.4:
        docker: *docker-node-8
        steps:
            - checkout
            - restore_cache: *restore-node-modules-cache
            - attach_workspace: { at: '.' }
            - run: yarn add typescript@2.4
            - run: yarn test

    test2.7:
        docker: *docker-node-8
        steps:
            - checkout
            - restore_cache: *restore-node-modules-cache
            - attach_workspace: { at: '.' }
            - run: yarn add typescript@2.7
            - run: yarn test

    test2.8:
        docker: *docker-node-8
        steps:
            - checkout
            - restore_cache: *restore-node-modules-cache
            - attach_workspace: { at: '.' }
            - run: yarn add typescript@2.8
            - run: yarn test

    test2.9:
        docker: *docker-node-
        steps:
            - checkout
            - restore_cache: *restore-node-modules-cache
            - attach_workspace: { at: '.' }
            - run: yarn add typescript@2.9
            - run: yarn test

    test3.0:
        docker: *docker-node-8
        steps:
            - checkout
            - restore_cache: *restore-node-modules-cache
            - attach_workspace: { at: '.' }
            - run: yarn add typescript@3.0.1
            - run: yarn test

    test3.1:
        docker: *docker-node-8
        steps:
            - checkout
            - restore_cache: *restore-node-modules-cache
            - attach_workspace: { at: '.' }
            - run: yarn add typescript@3.1
            - run: yarn test

    test3.2:
        docker: *docker-node-8
        steps:
            - checkout
            - restore_cache: *restore-node-modules-cache
            - attach_workspace: { at: '.' }
            - run: yarn add typescript@3.2
            - run: yarn test

    test3.3:
        docker: *docker-node-8
        steps:
            - checkout
            - restore_cache: *restore-node-modules-cache
            - attach_workspace: { at: '.' }
            - run: yarn add typescript@3.3
            - run: yarn test

    test3.4:
        docker: *docker-node-8
        steps:
            - checkout
            - restore_cache: *restore-node-modules-cache
            - attach_workspace: { at: '.' }
            - run: yarn add typescript@3.4
            - run: yarn test

    test3.5:
        docker: *docker-node-8
        steps:
            - checkout
            - restore_cache: *restore-node-modules-cache
            - attach_workspace: { at: '.' }
            - run: yarn add typescript@3.5
            - run: yarn test

    test3.6:
        docker: *docker-node-8
        steps:
            - checkout
            - restore_cache: *restore-node-modules-cache
            - attach_workspace: { at: '.' }
            - run: yarn add typescript@3.6

    test3.7:
        docker: *docker-node-8
        steps:
            - checkout
            - restore_cache: *restore-node-modules-cache
            - attach_workspace: { at: '.' }
            - run: yarn add typescript@3.7
            - run: yarn test

    test3.8:
        docker: *docker-node-8
        steps:
            - checkout
            - restore_cache: *restore-node-modules-cache
            - attach_workspace: { at: '.' }
            - run: yarn add typescript@3.8
            - run: yarn test
            - run: yarn test

    testRc:
        docker: *docker-node-lts
        steps:
            - checkout
            - restore_cache: *restore-node-modules-cache
            - attach_workspace: { at: '.' }
            - run: yarn add typescript@rc
            - run: yarn test

    testNext:
        docker: *docker-node-latest
        steps:
            - checkout
            - restore_cache: *restore-node-modules-cache
            - attach_workspace: { at: '.' }
            - run: yarn add typescript@next
            - run: yarn test

workflows:
    version: 2
    build_lint_test:
        jobs:
            - checkout-code
            - clean-lockfile:
                requires: [checkout-code]
            - build:
                requires: [checkout-code]
            - lint:
                  requires: [build]
            - test:
                  requires: [build]
            - test2.1:
                  requires: [build]
            - test2.4:
                  requires: [build]
            - test2.7:
                  requires: [build]
            - test2.8:
                  requires: [build]
            - test2.9:
                  requires: [build]
            - test3.0:
                  requires: [build]
            - test3.1:
                  requires: [build]
            - test3.2:
                  requires: [build]
            - test3.3:
                  requires: [build]
            - test3.4:
                  requires: [build]
            - test3.5:
                  requires: [build]
            - test3.6:
                  requires: [build]
            - test3.7:
                  requires: [build]
            - test3.8:
                  requires: [build]
            - testRc:
                  requires: [build]
            - testNext:
                  requires: [build]
